---
- hosts:
    - ses-nodes
  remote_user: root
  gather_facts: no
  tasks:
      - name: disable ipv6
        shell: |
            echo 1 > /proc/sys/net/ipv6/conf/eth0/disable_ipv6
            echo "net.ipv6.conf.all.disable_ipv6 = 1"  >> /etc/sysctl.conf
            echo "net.ipv6.conf.default.disable_ipv6 = 1"  >> /etc/sysctl.conf
            echo "net.ipv6.conf.lo.disable_ipv6 = 1"  >> /etc/sysctl.conf

            #      - name: remove ipv6 from hosts file
            #        shell: sed -i '/[iI][pP]v6/d' /etc/hosts
            #        args:
            #          warn: false

