---
- hosts:
    - salt-master
  remote_user: root
  gather_subset: network
  tasks:
      - name: install ntp
        shell: zypper install -y ntp
        args:
          warn: false

      - name: configure ntp
        blockinfile:
            dest: /etc/ntp.conf
            block: |
                server 0.opensuse.pool.ntp.org iburst
                server 1.opensuse.pool.ntp.org iburst
                server 2.opensuse.pool.ntp.org iburst
                server 3.opensuse.pool.ntp.org iburst

      - name: start ntpd 
        shell: |
            systemctl enable ntpd
            systemctl start ntpd

      - name: install salt master
        shell: zypper install -y salt-master
        args:
          warn: false

      - name: configure salt master
        shell: |             
            sed -i "/#interface: 0.0.0.0/c\interface: {{ ansible_default_ipv4.address }} " /etc/salt/master
            systemctl enable salt-master
            systemctl start salt-master
        args:
          warn: false

