---
- hosts:
    - ses-nodes
  remote_user: root
  gather_facts: no
  vars_files:
    - ./vars.yaml
  tasks:
      - name: install salt minion
        shell: zypper install -y salt-minion
        args:
          warn: false

      - name: set master on minions
        shell: |             
                sed -i "/^.master: /c\master: {{ salt_master_ip }} " /etc/salt/minion
                systemctl enable salt-minion
                systemctl start salt-minion
        args:
          warn: false
